junit:
   stage: test
   script:
      - mvn -B clean test
generate_artifacts:
   stage: deploy
   script:
      - xvfb-run mvn -B clean package
   artifacts:
      paths:
         - target/CAMS*.jar
