junit:
   stage: test
   script:
      - mvn -B clean test
generate_artifacts:
   stage: deploy
   script:
      - echo "API_KEY=$API_KEY" >> ./src/main/resources/.env
      - mvn -B clean package
   artifacts:
      paths:
         - target/CAMS*.jar
